# Generated by QLabs Track Editor
# Compact feature-aware export: only code required by this map is included.
# Workspace: Open Road
# Included: straight roads, lane-following guides

import math
import sys
from qvl.qlabs import QuanserInteractiveLabs
from qvl.spline_line import QLabsSplineLine
TRACK_DATA = {'format': 'qlabs_track_editor', 'version': '2.0.0-dev', 'units': 'meters', 'project': {'scale_name': '1:1', 'scale_factor': 1.0}, 'canvas': {'width_m': 80.0, 'height_m': 50.0}, 'scenery_fill': {'style': 'suburban', 'density': 'medium', 'roadside_reserve_m': 4.0, 'building_road_band_m': 18.0}, 'environment': {'enabled': False, 'weather': 'clear_skies', 'time_of_day': 12.0}, 'workspace_platform': {'enabled': False, 'profile': 'open_road'}, 'workspace': {'mode': 'open_road', 'label': 'Open Road', 'spline_z_m': 1.2, 'show_road_reference': True, 'show_navigation_regions': True, 'show_reference_points': True, 'show_reference_labels': True}, 'objects': [{'id': 'open-road-width-test', 'type': 'straight_road', 'x': 0.0, 'y': 0.0, 'rotation_deg': 0.0, 'length_m': 30.0, 'width_m': 8.4, 'guide_line': {'enabled': True, 'position': 'center', 'custom_offset_m': 0.0, 'width_m': 0.1, 'color': 'yellow', 'rgb': [255, 215, 0], 'style': 'solid', 'scale_width_with_project': True}}]}
WORKSPACE_SETTINGS = TRACK_DATA.get('workspace', {}) or {}
PLATFORM_SETTINGS = TRACK_DATA.get('workspace_platform', {}) or {}
PLATFORM_ENABLED = bool(PLATFORM_SETTINGS.get('enabled', False))
NATIVE_SPLINE_Z = float(WORKSPACE_SETTINGS.get('spline_z_m', 0.05))
TRACK_BASE_Z = float(PLATFORM_SETTINGS.get('top_z_m', 0.0)) if PLATFORM_ENABLED else NATIVE_SPLINE_Z
ROAD_COLOR = [75 / 255.0, 75 / 255.0, 75 / 255.0]
ROAD_Z = TRACK_BASE_Z + (0.01 if PLATFORM_ENABLED else 0.0)
MARKING_Z = ROAD_Z + 0.021
GUIDE_Z = ROAD_Z + 0.023
EDGE_COLOR = [240 / 255.0, 240 / 255.0, 240 / 255.0]
CENTER_COLOR = [255 / 255.0, 215 / 255.0, 0 / 255.0]
EDGE_INSET_DESIGN_M = 0.4
EDGE_LINE_WIDTH_DESIGN_M = 0.1
CENTER_LINE_WIDTH_DESIGN_M = 0.15
CENTER_DASH_LENGTH_DESIGN_M = 0.6
CENTER_DASH_GAP_DESIGN_M = 0.3
JOIN_MATCH_TOLERANCE_DESIGN_M = 0.08
JOIN_PATCH_LENGTH_DESIGN_M = 0.6
GUIDE_PRESET_RGB = {'yellow': [255, 215, 0], 'white': [255, 255, 255], 'blue': [60, 160, 255], 'red': [255, 80, 80]}
DASH_LENGTH_DESIGN_M = 1.5
DASH_GAP_DESIGN_M = 1.0

def clamp(value, low, high):
    return max(low, min(high, value))

def project_scale():
    return float(TRACK_DATA.get('project', {}).get('scale_factor', 1.0))

def rotate_local_world(local_x, local_y, editor_rotation_deg):
    angle = math.radians(-float(editor_rotation_deg))
    c = math.cos(angle)
    s = math.sin(angle)
    return (local_x * c - local_y * s, local_x * s + local_y * c)

def local_to_world_design(obj, local_x, local_y):
    rx, ry = rotate_local_world(local_x, local_y, obj.get('rotation_deg', 0.0))
    return (float(obj.get('x', 0.0)) + rx, float(obj.get('y', 0.0)) + ry)

def scaled_world_point(obj, local_x, local_y):
    scale = project_scale()
    x, y = local_to_world_design(obj, local_x, local_y)
    return (x * scale, y * scale)

def editor_yaw_to_qlabs_radians(editor_rotation_deg):
    return math.radians(-float(editor_rotation_deg))

def spawn_straight_spline(qlabs, p1, p2, width, color, z=ROAD_Z):
    spline = QLabsSplineLine(qlabs)
    spline.spawn(location=[0, 0, 0], scale=[1, 1, 1], configuration=QLabsSplineLine.LINEAR)
    spline.set_points(color=color, pointList=[[p1[0], p1[1], z, width], [p2[0], p2[1], z, width]], alignEndPointTangents=False)

def spawn_arc_spline(qlabs, center, yaw_rad, radius, start_angle_deg, end_angle_deg, width, color, z=ROAD_Z):
    spline = QLabsSplineLine(qlabs)
    spline.spawn(location=[center[0], center[1], z], rotation=[0, 0, yaw_rad], scale=[1, 1, 1], configuration=QLabsSplineLine.CURVE)
    sweep = abs(end_angle_deg - start_angle_deg)
    num_points = max(4, int(math.ceil(sweep / 12.0)) + 1)
    spline.arc_from_center_degrees(radius=radius, startAngle=start_angle_deg, endAngle=end_angle_deg, lineWidth=width, color=color, numSplinePoints=num_points)

def spawn_dashed_straight(qlabs, p1, p2, width, color, z=GUIDE_Z, dash_design_m=DASH_LENGTH_DESIGN_M, gap_design_m=DASH_GAP_DESIGN_M):
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    length = math.hypot(dx, dy)
    if length <= 1e-09:
        return
    ux = dx / length
    uy = dy / length
    scale = project_scale()
    dash = max(0.003, float(dash_design_m) * scale)
    gap = max(0.002, float(gap_design_m) * scale)
    cursor = 0.0
    while cursor < length - 1e-09:
        end = min(length, cursor + dash)
        a = (p1[0] + ux * cursor, p1[1] + uy * cursor)
        b = (p1[0] + ux * end, p1[1] + uy * end)
        spawn_straight_spline(qlabs, a, b, width, color, z=z)
        cursor = end + gap

def spawn_dashed_arc(qlabs, center, yaw_rad, radius, turn_angle_deg, width, color, z=GUIDE_Z, dash_design_m=DASH_LENGTH_DESIGN_M, gap_design_m=DASH_GAP_DESIGN_M):
    total_length = abs(math.radians(turn_angle_deg) * radius)
    if total_length <= 1e-09 or radius <= 1e-09:
        return
    scale = project_scale()
    dash = max(0.003, float(dash_design_m) * scale)
    gap = max(0.002, float(gap_design_m) * scale)
    cursor = 0.0
    while cursor < total_length - 1e-09:
        end = min(total_length, cursor + dash)
        start_angle = 90.0 - math.degrees(cursor / radius)
        end_angle = 90.0 - math.degrees(end / radius)
        spawn_arc_spline(qlabs, center=center, yaw_rad=yaw_rad, radius=radius, start_angle_deg=start_angle, end_angle_deg=end_angle, width=width, color=color, z=z)
        cursor = end + gap

def resolved_guide_offset_design(obj):
    guide = obj.get('guide_line', {}) or {}
    position = str(guide.get('position', 'left'))
    road_width = float(obj.get('width_m', 6.0))
    if position == 'left':
        return -road_width / 4.0
    if position == 'right':
        return road_width / 4.0
    if position == 'center':
        return 0.0
    return float(guide.get('custom_offset_m', -road_width / 4.0))

def guide_color(obj):
    guide = obj.get('guide_line', {}) or {}
    name = str(guide.get('color', 'yellow'))
    if name == 'custom':
        rgb = guide.get('rgb', [255, 215, 0])
    else:
        rgb = GUIDE_PRESET_RGB.get(name, GUIDE_PRESET_RGB['yellow'])
    if not isinstance(rgb, (list, tuple)) or len(rgb) != 3:
        rgb = [255, 215, 0]
    return [clamp(float(rgb[0]), 0.0, 255.0) / 255.0, clamp(float(rgb[1]), 0.0, 255.0) / 255.0, clamp(float(rgb[2]), 0.0, 255.0) / 255.0]

def guide_width_effective(obj):
    guide = obj.get('guide_line', {}) or {}
    width = max(0.001, float(guide.get('width_m', 0.1)))
    if bool(guide.get('scale_width_with_project', True)):
        width *= project_scale()
    return width

def curve_center_design_local(radius_design, turn_angle_deg):
    theta = math.radians(turn_angle_deg)
    cx = -0.5 * radius_design * math.sin(theta)
    cy = -0.5 * radius_design * (1.0 + math.cos(theta))
    return (cx, cy)

def spawn_road_surface(qlabs, obj):
    obj_type = str(obj.get('type', ''))
    scale = project_scale()
    width = max(0.001, float(obj.get('width_m', 6.0)) * scale)
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        p1 = scaled_world_point(obj, -length / 2.0, 0.0)
        p2 = scaled_world_point(obj, length / 2.0, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        return
    if obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        p1 = scaled_world_point(obj, -length / 2.0, 0.0)
        p2 = scaled_world_point(obj, length / 2.0, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        return
    if obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        radius_design = float(obj.get('radius_m', 10.0))
        local_center = curve_center_design_local(radius_design, turn)
        center = scaled_world_point(obj, local_center[0], local_center[1])
        spawn_arc_spline(qlabs, center=center, yaw_rad=editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0)), radius=radius_design * scale, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=width, color=ROAD_COLOR, z=ROAD_Z)
        return
    if obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        p1 = scaled_world_point(obj, -arm, 0.0)
        p2 = scaled_world_point(obj, arm, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        p3 = scaled_world_point(obj, 0.0, 0.0)
        p4 = scaled_world_point(obj, 0.0, -arm)
        spawn_straight_spline(qlabs, p3, p4, width, ROAD_COLOR)
        return
    if obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        p1 = scaled_world_point(obj, -arm, 0.0)
        p2 = scaled_world_point(obj, arm, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        p3 = scaled_world_point(obj, 0.0, arm)
        p4 = scaled_world_point(obj, 0.0, -arm)
        spawn_straight_spline(qlabs, p3, p4, width, ROAD_COLOR)

def marking_width_effective(design_width_m):
    return max(0.001, float(design_width_m) * project_scale())

def spawn_center_dashes_straight(qlabs, obj, p1_local, p2_local):
    p1 = scaled_world_point(obj, p1_local[0], p1_local[1])
    p2 = scaled_world_point(obj, p2_local[0], p2_local[1])
    spawn_dashed_straight(qlabs, p1, p2, marking_width_effective(CENTER_LINE_WIDTH_DESIGN_M), CENTER_COLOR, z=MARKING_Z, dash_design_m=CENTER_DASH_LENGTH_DESIGN_M, gap_design_m=CENTER_DASH_GAP_DESIGN_M)

def spawn_road_markings(qlabs, obj):
    """Export the markings drawn by the editor for each road component."""
    obj_type = str(obj.get('type', ''))
    scale = project_scale()
    edge_width = marking_width_effective(EDGE_LINE_WIDTH_DESIGN_M)
    road_width_design = float(obj.get('width_m', 6.0))
    half_width = road_width_design / 2.0
    edge_offset = max(0.01, half_width - EDGE_INSET_DESIGN_M)
    markings = obj.get('road_markings', {}) or {}
    show_edge_a = bool(markings.get('edge_a', True))
    show_center = bool(markings.get('center', True))
    show_edge_b = bool(markings.get('edge_b', True))
    show_end_bar = bool(markings.get('end_bar', True))
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        for enabled, local_y in ((show_edge_a, +edge_offset), (show_edge_b, -edge_offset)):
            if not enabled:
                continue
            p1 = scaled_world_point(obj, -length / 2.0, local_y)
            p2 = scaled_world_point(obj, length / 2.0, local_y)
            spawn_straight_spline(qlabs, p1, p2, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_center:
            spawn_center_dashes_straight(qlabs, obj, (-length / 2.0, 0.0), (length / 2.0, 0.0))
        return
    if obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        for enabled, local_y in ((show_edge_a, +edge_offset), (show_edge_b, -edge_offset)):
            if not enabled:
                continue
            p1 = scaled_world_point(obj, -length / 2.0, local_y)
            p2 = scaled_world_point(obj, length / 2.0, local_y)
            spawn_straight_spline(qlabs, p1, p2, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_center:
            spawn_center_dashes_straight(qlabs, obj, (-length / 2.0, 0.0), (length / 2.0 - 0.9, 0.0))
        if show_end_bar:
            end_x = length / 2.0 - 0.3
            a = scaled_world_point(obj, end_x, +edge_offset)
            b = scaled_world_point(obj, end_x, -edge_offset)
            spawn_straight_spline(qlabs, a, b, marking_width_effective(0.2), EDGE_COLOR, z=MARKING_Z)
        return
    if obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        radius_design = float(obj.get('radius_m', 10.0))
        local_center = curve_center_design_local(radius_design, turn)
        center = scaled_world_point(obj, local_center[0], local_center[1])
        yaw = editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0))
        outer_radius = (radius_design + edge_offset) * scale
        inner_radius = max(0.001, (radius_design - edge_offset) * scale)
        if show_edge_a:
            spawn_arc_spline(qlabs, center=center, yaw_rad=yaw, radius=outer_radius, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=edge_width, color=EDGE_COLOR, z=MARKING_Z)
        if show_edge_b:
            spawn_arc_spline(qlabs, center=center, yaw_rad=yaw, radius=inner_radius, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=edge_width, color=EDGE_COLOR, z=MARKING_Z)
        if show_center:
            spawn_dashed_arc(qlabs, center=center, yaw_rad=yaw, radius=radius_design * scale, turn_angle_deg=turn, width=marking_width_effective(CENTER_LINE_WIDTH_DESIGN_M), color=CENTER_COLOR, z=MARKING_Z, dash_design_m=CENTER_DASH_LENGTH_DESIGN_M, gap_design_m=CENTER_DASH_GAP_DESIGN_M)
        return
    if obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        if show_edge_a:
            a = scaled_world_point(obj, -arm, +edge_offset)
            b = scaled_world_point(obj, arm, +edge_offset)
            spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
            a = scaled_world_point(obj, -edge_offset, -half_width)
            b = scaled_world_point(obj, -edge_offset, -arm)
            spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_edge_b:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                a = scaled_world_point(obj, x1, -edge_offset)
                b = scaled_world_point(obj, x2, -edge_offset)
                spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
            a = scaled_world_point(obj, +edge_offset, -half_width)
            b = scaled_world_point(obj, +edge_offset, -arm)
            spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_center:
            spawn_center_dashes_straight(qlabs, obj, (-arm, 0.0), (-half_width, 0.0))
            spawn_center_dashes_straight(qlabs, obj, (half_width, 0.0), (arm, 0.0))
            spawn_center_dashes_straight(qlabs, obj, (0.0, -half_width), (0.0, -arm))
        return
    if obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        if show_edge_a:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                a = scaled_world_point(obj, x1, +edge_offset)
                b = scaled_world_point(obj, x2, +edge_offset)
                spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
            for y1, y2 in ((arm, half_width), (-half_width, -arm)):
                a = scaled_world_point(obj, -edge_offset, y1)
                b = scaled_world_point(obj, -edge_offset, y2)
                spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_edge_b:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                a = scaled_world_point(obj, x1, -edge_offset)
                b = scaled_world_point(obj, x2, -edge_offset)
                spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
            for y1, y2 in ((arm, half_width), (-half_width, -arm)):
                a = scaled_world_point(obj, +edge_offset, y1)
                b = scaled_world_point(obj, +edge_offset, y2)
                spawn_straight_spline(qlabs, a, b, edge_width, EDGE_COLOR, z=MARKING_Z)
        if show_center:
            spawn_center_dashes_straight(qlabs, obj, (-arm, 0.0), (-half_width, 0.0))
            spawn_center_dashes_straight(qlabs, obj, (half_width, 0.0), (arm, 0.0))
            spawn_center_dashes_straight(qlabs, obj, (0.0, arm), (0.0, half_width))
            spawn_center_dashes_straight(qlabs, obj, (0.0, -half_width), (0.0, -arm))
        return

def _rotate_vector_world(vx, vy, editor_rotation_deg):
    """Rotate a local world vector by the object's editor rotation."""
    return rotate_local_world(vx, vy, editor_rotation_deg)

def _connection_points_design(obj):
    """Return connectable road endpoints in full-scale design coordinates.

    Each entry contains:
      x, y      world/design position
      tx, ty    unit tangent axis (direction sign is irrelevant)
      width_m   road width
    """
    obj_type = str(obj.get('type', ''))
    width = float(obj.get('width_m', 6.0))
    rotation = float(obj.get('rotation_deg', 0.0))
    local = []
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        local = [(-length / 2.0, 0.0, 1.0, 0.0), (length / 2.0, 0.0, 1.0, 0.0)]
    elif obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        local = [(-length / 2.0, 0.0, 1.0, 0.0)]
    elif obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        theta = math.radians(turn)
        radius = float(obj.get('radius_m', 10.0))
        dx = radius * math.sin(theta)
        dy = radius * (1.0 - math.cos(theta))
        local = [(-dx / 2.0, +dy / 2.0, 1.0, 0.0), (+dx / 2.0, -dy / 2.0, math.cos(theta), -math.sin(theta))]
    elif obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        local = [(-arm, 0.0, 1.0, 0.0), (+arm, 0.0, 1.0, 0.0), (0.0, -arm, 0.0, 1.0)]
    elif obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        local = [(-arm, 0.0, 1.0, 0.0), (+arm, 0.0, 1.0, 0.0), (0.0, +arm, 0.0, 1.0), (0.0, -arm, 0.0, 1.0)]
    else:
        return []
    result = []
    for lx, ly, ltx, lty in local:
        x, y = local_to_world_design(obj, lx, ly)
        tx, ty = _rotate_vector_world(ltx, lty, rotation)
        mag = math.hypot(tx, ty)
        if mag <= 1e-09:
            continue
        result.append({'x': x, 'y': y, 'tx': tx / mag, 'ty': ty / mag, 'width_m': width, 'object_id': obj.get('id')})
    return result

def _axis_alignment(a, b):
    """Return absolute tangent-axis alignment in [0,1]."""
    return abs(a['tx'] * b['tx'] + a['ty'] * b['ty'])

def spawn_connection_patches(qlabs, objects):
    """Bridge tiny rendering seams only at actual road connections."""
    endpoints = []
    for obj in objects:
        endpoints.extend(_connection_points_design(obj))
    used_pairs = set()
    for i, a in enumerate(endpoints):
        for j in range(i + 1, len(endpoints)):
            b = endpoints[j]
            if a.get('object_id') == b.get('object_id'):
                continue
            dx = b['x'] - a['x']
            dy = b['y'] - a['y']
            distance = math.hypot(dx, dy)
            if distance > JOIN_MATCH_TOLERANCE_DESIGN_M:
                continue
            if _axis_alignment(a, b) < math.cos(math.radians(12.0)):
                continue
            pair_key = tuple(sorted((i, j)))
            if pair_key in used_pairs:
                continue
            used_pairs.add(pair_key)
            cx_design = (a['x'] + b['x']) / 2.0
            cy_design = (a['y'] + b['y']) / 2.0
            dot = a['tx'] * b['tx'] + a['ty'] * b['ty']
            sign = 1.0 if dot >= 0.0 else -1.0
            tx = a['tx'] + sign * b['tx']
            ty = a['ty'] + sign * b['ty']
            mag = math.hypot(tx, ty)
            if mag <= 1e-09:
                tx, ty = (a['tx'], a['ty'])
            else:
                tx /= mag
                ty /= mag
            half_patch = JOIN_PATCH_LENGTH_DESIGN_M / 2.0
            p1_design = (cx_design - tx * half_patch, cy_design - ty * half_patch)
            p2_design = (cx_design + tx * half_patch, cy_design + ty * half_patch)
            scale = project_scale()
            p1 = (p1_design[0] * scale, p1_design[1] * scale)
            p2 = (p2_design[0] * scale, p2_design[1] * scale)
            patch_width = max(a['width_m'], b['width_m']) * scale
            spawn_straight_spline(qlabs, p1, p2, patch_width, ROAD_COLOR, z=ROAD_Z + 0.0005)

def spawn_guide(qlabs, obj):
    guide = obj.get('guide_line', {}) or {}
    if not bool(guide.get('enabled', False)):
        return
    obj_type = str(obj.get('type', ''))
    if obj_type not in ('straight_road', 'road_end', 'curve_45', 'curve_90', 't_junction', 'cross_intersection'):
        return
    style = str(guide.get('style', 'solid'))
    width = guide_width_effective(obj)
    color = guide_color(obj)
    offset_design = resolved_guide_offset_design(obj)
    if obj_type in ('straight_road', 'road_end'):
        length = float(obj.get('length_m', 20.0))
        local_y_world = -offset_design
        start_x = -length / 2.0
        end_x = length / 2.0
        if obj_type == 'road_end':
            end_x -= min(0.9, max(0.0, length * 0.25))
        p1 = scaled_world_point(obj, start_x, local_y_world)
        p2 = scaled_world_point(obj, end_x, local_y_world)
        if style == 'dashed':
            spawn_dashed_straight(qlabs, p1, p2, width, color, z=GUIDE_Z)
        else:
            spawn_straight_spline(qlabs, p1, p2, width, color, z=GUIDE_Z)
        return
    if obj_type in ('t_junction', 'cross_intersection'):
        arm = float(obj.get('arm_length_m', 12.0))
        horizontal_y = -offset_design
        vertical_x = -offset_design
        horizontal_p1 = scaled_world_point(obj, -arm, horizontal_y)
        horizontal_p2 = scaled_world_point(obj, arm, horizontal_y)

        def _spawn_junction_guide_segment(p1, p2):
            if style == 'dashed':
                spawn_dashed_straight(qlabs, p1, p2, width, color, z=GUIDE_Z)
            else:
                spawn_straight_spline(qlabs, p1, p2, width, color, z=GUIDE_Z)
        _spawn_junction_guide_segment(horizontal_p1, horizontal_p2)
        if obj_type == 't_junction':
            vertical_p1 = scaled_world_point(obj, vertical_x, 0.0)
            vertical_p2 = scaled_world_point(obj, vertical_x, -arm)
        else:
            vertical_p1 = scaled_world_point(obj, vertical_x, arm)
            vertical_p2 = scaled_world_point(obj, vertical_x, -arm)
        _spawn_junction_guide_segment(vertical_p1, vertical_p2)
        return
    turn = 45.0 if obj_type == 'curve_45' else 90.0
    radius_design = float(obj.get('radius_m', 10.0))
    local_center = curve_center_design_local(radius_design, turn)
    center = scaled_world_point(obj, local_center[0], local_center[1])
    guide_radius_design = max(0.1, radius_design - offset_design)
    guide_radius = guide_radius_design * project_scale()
    yaw = editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0))
    if style == 'dashed':
        spawn_dashed_arc(qlabs, center=center, yaw_rad=yaw, radius=guide_radius, turn_angle_deg=turn, width=width, color=color, z=GUIDE_Z)
    else:
        spawn_arc_spline(qlabs, center=center, yaw_rad=yaw, radius=guide_radius, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=width, color=color, z=GUIDE_Z)

def main():
    print('Connecting to QLabs...')
    qlabs = QuanserInteractiveLabs()
    if not qlabs.open('localhost'):
        print('Unable to connect to QLabs.')
        print('Open QLabs in the Open Road workspace and try again.')
        sys.exit(1)
    print('Connected to QLabs.')
    qlabs.destroy_all_spawned_actors()
    objects = TRACK_DATA.get('objects', [])
    for obj in objects:
        spawn_road_surface(qlabs, obj)
    spawn_connection_patches(qlabs, objects)
    for obj in objects:
        spawn_road_markings(qlabs, obj)
    for obj in objects:
        spawn_guide(qlabs, obj)
    print('QLabs track created. Project scale = ' + str(TRACK_DATA.get('project', {}).get('scale_name', '1:1')))
if __name__ == '__main__':
    main()
