# Generated by QLabs Track Editor
# Compact feature-aware export: only code required by this map is included.
# Workspace: Open Road
# Included: straight roads

import math
import sys
from qvl.qlabs import QuanserInteractiveLabs
from qvl.spline_line import QLabsSplineLine
from qvl.basic_shape import QLabsBasicShape
TRACK_DATA = {'format': 'qlabs_track_editor', 'version': '2.0.0-dev', 'units': 'meters', 'project': {'scale_name': '1:1', 'scale_factor': 1.0}, 'canvas': {'width_m': 80.0, 'height_m': 50.0}, 'workspace': {'mode': 'open_road', 'label': 'Open Road', 'spline_z_m': 1.2, 'show_road_reference': True}, 'workspace_platform': {'enabled': False, 'profile': 'open_road'}, 'environment': {'enabled': False, 'weather': 'clear_skies', 'time_of_day': 12.0}, 'objects': [{'type': 'median_wall', 'id': 'wall', 'x': 0, 'y': 0, 'rotation_deg': 0, 'length_m': 30, 'width_m': 0.5, 'height_m': 0.85}, {'type': 'straight_road', 'id': 'r1', 'x': 0, 'y': 4.45, 'rotation_deg': 0, 'length_m': 30, 'width_m': 8.4, 'road_markings': {'edge_a': True, 'edge_a_color': 'red', 'edge_a_style': 'dashed', 'center': True, 'center_color': 'white', 'center_style': 'solid', 'edge_b': False, 'edge_b_color': 'blue', 'edge_b_style': 'solid', 'end_bar': True, 'end_bar_color': 'white', 'end_bar_style': 'solid'}, 'guide_line': {'enabled': False}}, {'type': 'straight_road', 'id': 'r2', 'x': 0, 'y': -4.45, 'rotation_deg': 0, 'length_m': 30, 'width_m': 8.4, 'road_markings': {'edge_a': False, 'edge_a_color': 'white', 'edge_a_style': 'solid', 'center': True, 'center_color': 'yellow', 'center_style': 'dashed', 'edge_b': True, 'edge_b_color': 'blue', 'edge_b_style': 'dashed', 'end_bar': True, 'end_bar_color': 'white', 'end_bar_style': 'solid'}, 'guide_line': {'enabled': False}}]}
WORKSPACE_SETTINGS = TRACK_DATA.get('workspace', {}) or {}
PLATFORM_SETTINGS = TRACK_DATA.get('workspace_platform', {}) or {}
PLATFORM_ENABLED = bool(PLATFORM_SETTINGS.get('enabled', False))
NATIVE_SPLINE_Z = float(WORKSPACE_SETTINGS.get('spline_z_m', 1.2))
TRACK_BASE_Z = float(PLATFORM_SETTINGS.get('top_z_m', 0.0)) if PLATFORM_ENABLED else NATIVE_SPLINE_Z
ACTOR_HANDLES = {}
ROAD_COLOR = [75 / 255.0, 75 / 255.0, 75 / 255.0]
ROAD_Z = TRACK_BASE_Z + (0.01 if PLATFORM_ENABLED else 0.0)
MARKING_Z = ROAD_Z + 0.021
GUIDE_Z = ROAD_Z + 0.023
MARKING_PRESET_RGB = {'white': [240, 240, 240], 'yellow': [255, 215, 0], 'blue': [60, 160, 255], 'red': [255, 80, 80], 'black': [25, 25, 25]}
EDGE_INSET_DESIGN_M = 0.4
EDGE_LINE_WIDTH_DESIGN_M = 0.1
CENTER_LINE_WIDTH_DESIGN_M = 0.15
CENTER_DASH_LENGTH_DESIGN_M = 0.6
CENTER_DASH_GAP_DESIGN_M = 0.3
JOIN_MATCH_TOLERANCE_DESIGN_M = 0.08
JOIN_PATCH_LENGTH_DESIGN_M = 0.6
DASH_LENGTH_DESIGN_M = 1.5
DASH_GAP_DESIGN_M = 1.0

def project_scale():
    return float(TRACK_DATA.get('project', {}).get('scale_factor', 1.0))

def rotate_local_world(local_x, local_y, editor_rotation_deg):
    angle = math.radians(-float(editor_rotation_deg))
    c = math.cos(angle)
    s = math.sin(angle)
    return (local_x * c - local_y * s, local_x * s + local_y * c)

def local_to_world_design(obj, local_x, local_y):
    rx, ry = rotate_local_world(local_x, local_y, obj.get('rotation_deg', 0.0))
    return (float(obj.get('x', 0.0)) + rx, float(obj.get('y', 0.0)) + ry)

def scaled_world_point(obj, local_x, local_y):
    scale = project_scale()
    x, y = local_to_world_design(obj, local_x, local_y)
    return (x * scale, y * scale)

def editor_yaw_to_qlabs_radians(editor_rotation_deg):
    return math.radians(-float(editor_rotation_deg))

def spawn_straight_spline(qlabs, p1, p2, width, color, z=ROAD_Z):
    spline = QLabsSplineLine(qlabs)
    spline.spawn(location=[0, 0, 0], scale=[1, 1, 1], configuration=QLabsSplineLine.LINEAR)
    spline.set_points(color=color, pointList=[[p1[0], p1[1], z, width], [p2[0], p2[1], z, width]], alignEndPointTangents=False)

def spawn_arc_spline(qlabs, center, yaw_rad, radius, start_angle_deg, end_angle_deg, width, color, z=ROAD_Z):
    spline = QLabsSplineLine(qlabs)
    spline.spawn(location=[center[0], center[1], z], rotation=[0, 0, yaw_rad], scale=[1, 1, 1], configuration=QLabsSplineLine.CURVE)
    sweep = abs(end_angle_deg - start_angle_deg)
    num_points = max(4, int(math.ceil(sweep / 12.0)) + 1)
    spline.arc_from_center_degrees(radius=radius, startAngle=start_angle_deg, endAngle=end_angle_deg, lineWidth=width, color=color, numSplinePoints=num_points)

def spawn_dashed_straight(qlabs, p1, p2, width, color, z=GUIDE_Z, dash_design_m=DASH_LENGTH_DESIGN_M, gap_design_m=DASH_GAP_DESIGN_M):
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    length = math.hypot(dx, dy)
    if length <= 1e-09:
        return
    ux = dx / length
    uy = dy / length
    scale = project_scale()
    dash = max(0.003, float(dash_design_m) * scale)
    gap = max(0.002, float(gap_design_m) * scale)
    cursor = 0.0
    while cursor < length - 1e-09:
        end = min(length, cursor + dash)
        a = (p1[0] + ux * cursor, p1[1] + uy * cursor)
        b = (p1[0] + ux * end, p1[1] + uy * end)
        spawn_straight_spline(qlabs, a, b, width, color, z=z)
        cursor = end + gap

def spawn_dashed_arc(qlabs, center, yaw_rad, radius, turn_angle_deg, width, color, z=GUIDE_Z, dash_design_m=DASH_LENGTH_DESIGN_M, gap_design_m=DASH_GAP_DESIGN_M):
    total_length = abs(math.radians(turn_angle_deg) * radius)
    if total_length <= 1e-09 or radius <= 1e-09:
        return
    scale = project_scale()
    dash = max(0.003, float(dash_design_m) * scale)
    gap = max(0.002, float(gap_design_m) * scale)
    cursor = 0.0
    while cursor < total_length - 1e-09:
        end = min(total_length, cursor + dash)
        start_angle = 90.0 - math.degrees(cursor / radius)
        end_angle = 90.0 - math.degrees(end / radius)
        spawn_arc_spline(qlabs, center=center, yaw_rad=yaw_rad, radius=radius, start_angle_deg=start_angle, end_angle_deg=end_angle, width=width, color=color, z=z)
        cursor = end + gap

def curve_center_design_local(radius_design, turn_angle_deg):
    theta = math.radians(turn_angle_deg)
    cx = -0.5 * radius_design * math.sin(theta)
    cy = -0.5 * radius_design * (1.0 + math.cos(theta))
    return (cx, cy)

def spawn_road_surface(qlabs, obj):
    obj_type = str(obj.get('type', ''))
    scale = project_scale()
    width = max(0.001, float(obj.get('width_m', 6.0)) * scale)
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        p1 = scaled_world_point(obj, -length / 2.0, 0.0)
        p2 = scaled_world_point(obj, length / 2.0, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        return
    if obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        p1 = scaled_world_point(obj, -length / 2.0, 0.0)
        p2 = scaled_world_point(obj, length / 2.0, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        return
    if obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        radius_design = float(obj.get('radius_m', 10.0))
        local_center = curve_center_design_local(radius_design, turn)
        center = scaled_world_point(obj, local_center[0], local_center[1])
        spawn_arc_spline(qlabs, center=center, yaw_rad=editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0)), radius=radius_design * scale, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=width, color=ROAD_COLOR, z=ROAD_Z)
        return
    if obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        p1 = scaled_world_point(obj, -arm, 0.0)
        p2 = scaled_world_point(obj, arm, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        p3 = scaled_world_point(obj, 0.0, 0.0)
        p4 = scaled_world_point(obj, 0.0, -arm)
        spawn_straight_spline(qlabs, p3, p4, width, ROAD_COLOR)
        return
    if obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        p1 = scaled_world_point(obj, -arm, 0.0)
        p2 = scaled_world_point(obj, arm, 0.0)
        spawn_straight_spline(qlabs, p1, p2, width, ROAD_COLOR)
        p3 = scaled_world_point(obj, 0.0, arm)
        p4 = scaled_world_point(obj, 0.0, -arm)
        spawn_straight_spline(qlabs, p3, p4, width, ROAD_COLOR)

def marking_width_effective(design_width_m):
    return max(0.001, float(design_width_m) * project_scale())

def marking_color(markings, key, default_name):
    name = str(markings.get(f'{key}_color', default_name))
    rgb = MARKING_PRESET_RGB.get(name, MARKING_PRESET_RGB[default_name])
    return [value / 255.0 for value in rgb]

def marking_style(markings, key, default_style):
    style = str(markings.get(f'{key}_style', default_style))
    return 'dashed' if style == 'dashed' else 'solid'

def spawn_marking_straight(qlabs, p1, p2, width, color, style):
    if style == 'dashed':
        spawn_dashed_straight(qlabs, p1, p2, width, color, z=MARKING_Z, dash_design_m=CENTER_DASH_LENGTH_DESIGN_M, gap_design_m=CENTER_DASH_GAP_DESIGN_M)
    else:
        spawn_straight_spline(qlabs, p1, p2, width, color, z=MARKING_Z)

def spawn_marking_local_straight(qlabs, obj, p1_local, p2_local, width, color, style):
    p1 = scaled_world_point(obj, p1_local[0], p1_local[1])
    p2 = scaled_world_point(obj, p2_local[0], p2_local[1])
    spawn_marking_straight(qlabs, p1, p2, width, color, style)

def spawn_marking_arc(qlabs, center, yaw, radius, turn, width, color, style):
    if style == 'dashed':
        spawn_dashed_arc(qlabs, center=center, yaw_rad=yaw, radius=radius, turn_angle_deg=turn, width=width, color=color, z=MARKING_Z, dash_design_m=CENTER_DASH_LENGTH_DESIGN_M, gap_design_m=CENTER_DASH_GAP_DESIGN_M)
    else:
        spawn_arc_spline(qlabs, center=center, yaw_rad=yaw, radius=radius, start_angle_deg=90.0, end_angle_deg=90.0 - turn, width=width, color=color, z=MARKING_Z)

def spawn_road_markings(qlabs, obj):
    """Export each road marking with its own visibility/color/style."""
    obj_type = str(obj.get('type', ''))
    scale = project_scale()
    edge_width = marking_width_effective(EDGE_LINE_WIDTH_DESIGN_M)
    center_width = marking_width_effective(CENTER_LINE_WIDTH_DESIGN_M)
    road_width_design = float(obj.get('width_m', 8.4))
    half_width = road_width_design / 2.0
    edge_offset = max(0.01, half_width - EDGE_INSET_DESIGN_M)
    markings = obj.get('road_markings', {}) or {}
    show_edge_a = bool(markings.get('edge_a', True))
    show_center = bool(markings.get('center', True))
    show_edge_b = bool(markings.get('edge_b', True))
    show_end_bar = bool(markings.get('end_bar', True))
    edge_a_color = marking_color(markings, 'edge_a', 'white')
    edge_a_style = marking_style(markings, 'edge_a', 'solid')
    center_color = marking_color(markings, 'center', 'yellow')
    center_style = marking_style(markings, 'center', 'dashed')
    edge_b_color = marking_color(markings, 'edge_b', 'white')
    edge_b_style = marking_style(markings, 'edge_b', 'solid')
    end_color = marking_color(markings, 'end_bar', 'white')
    end_style = marking_style(markings, 'end_bar', 'solid')
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        if show_edge_a:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, +edge_offset), (length / 2.0, +edge_offset), edge_width, edge_a_color, edge_a_style)
        if show_edge_b:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, -edge_offset), (length / 2.0, -edge_offset), edge_width, edge_b_color, edge_b_style)
        if show_center:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, 0.0), (length / 2.0, 0.0), center_width, center_color, center_style)
        return
    if obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        if show_edge_a:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, +edge_offset), (length / 2.0, +edge_offset), edge_width, edge_a_color, edge_a_style)
        if show_edge_b:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, -edge_offset), (length / 2.0, -edge_offset), edge_width, edge_b_color, edge_b_style)
        if show_center:
            spawn_marking_local_straight(qlabs, obj, (-length / 2.0, 0.0), (length / 2.0 - 0.9, 0.0), center_width, center_color, center_style)
        if show_end_bar:
            end_x = length / 2.0 - 0.3
            spawn_marking_local_straight(qlabs, obj, (end_x, +edge_offset), (end_x, -edge_offset), marking_width_effective(0.2), end_color, end_style)
        return
    if obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        radius_design = float(obj.get('radius_m', 10.0))
        local_center = curve_center_design_local(radius_design, turn)
        center = scaled_world_point(obj, local_center[0], local_center[1])
        yaw = editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0))
        outer_radius = (radius_design + edge_offset) * scale
        inner_radius = max(0.001, (radius_design - edge_offset) * scale)
        if show_edge_a:
            spawn_marking_arc(qlabs, center, yaw, outer_radius, turn, edge_width, edge_a_color, edge_a_style)
        if show_edge_b:
            spawn_marking_arc(qlabs, center, yaw, inner_radius, turn, edge_width, edge_b_color, edge_b_style)
        if show_center:
            spawn_marking_arc(qlabs, center, yaw, radius_design * scale, turn, center_width, center_color, center_style)
        return
    if obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        if show_edge_a:
            spawn_marking_local_straight(qlabs, obj, (-arm, +edge_offset), (arm, +edge_offset), edge_width, edge_a_color, edge_a_style)
            spawn_marking_local_straight(qlabs, obj, (-edge_offset, -half_width), (-edge_offset, -arm), edge_width, edge_a_color, edge_a_style)
        if show_edge_b:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                spawn_marking_local_straight(qlabs, obj, (x1, -edge_offset), (x2, -edge_offset), edge_width, edge_b_color, edge_b_style)
            spawn_marking_local_straight(qlabs, obj, (+edge_offset, -half_width), (+edge_offset, -arm), edge_width, edge_b_color, edge_b_style)
        if show_center:
            for a, b in (((-arm, 0.0), (-half_width, 0.0)), ((half_width, 0.0), (arm, 0.0)), ((0.0, -half_width), (0.0, -arm))):
                spawn_marking_local_straight(qlabs, obj, a, b, center_width, center_color, center_style)
        return
    if obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        if show_edge_a:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                spawn_marking_local_straight(qlabs, obj, (x1, +edge_offset), (x2, +edge_offset), edge_width, edge_a_color, edge_a_style)
            for y1, y2 in ((arm, half_width), (-half_width, -arm)):
                spawn_marking_local_straight(qlabs, obj, (-edge_offset, y1), (-edge_offset, y2), edge_width, edge_a_color, edge_a_style)
        if show_edge_b:
            for x1, x2 in ((-arm, -half_width), (half_width, arm)):
                spawn_marking_local_straight(qlabs, obj, (x1, -edge_offset), (x2, -edge_offset), edge_width, edge_b_color, edge_b_style)
            for y1, y2 in ((arm, half_width), (-half_width, -arm)):
                spawn_marking_local_straight(qlabs, obj, (+edge_offset, y1), (+edge_offset, y2), edge_width, edge_b_color, edge_b_style)
        if show_center:
            for a, b in (((-arm, 0.0), (-half_width, 0.0)), ((half_width, 0.0), (arm, 0.0)), ((0.0, arm), (0.0, half_width)), ((0.0, -half_width), (0.0, -arm))):
                spawn_marking_local_straight(qlabs, obj, a, b, center_width, center_color, center_style)
        return

def _rotate_vector_world(vx, vy, editor_rotation_deg):
    """Rotate a local world vector by the object's editor rotation."""
    return rotate_local_world(vx, vy, editor_rotation_deg)

def _connection_points_design(obj):
    """Return connectable road endpoints in full-scale design coordinates.

    Each entry contains:
      x, y      world/design position
      tx, ty    unit tangent axis (direction sign is irrelevant)
      width_m   road width
    """
    obj_type = str(obj.get('type', ''))
    width = float(obj.get('width_m', 6.0))
    rotation = float(obj.get('rotation_deg', 0.0))
    local = []
    if obj_type == 'straight_road':
        length = float(obj.get('length_m', 20.0))
        local = [(-length / 2.0, 0.0, 1.0, 0.0), (length / 2.0, 0.0, 1.0, 0.0)]
    elif obj_type == 'road_end':
        length = float(obj.get('length_m', 8.0))
        local = [(-length / 2.0, 0.0, 1.0, 0.0)]
    elif obj_type in ('curve_45', 'curve_90'):
        turn = 45.0 if obj_type == 'curve_45' else 90.0
        theta = math.radians(turn)
        radius = float(obj.get('radius_m', 10.0))
        dx = radius * math.sin(theta)
        dy = radius * (1.0 - math.cos(theta))
        local = [(-dx / 2.0, +dy / 2.0, 1.0, 0.0), (+dx / 2.0, -dy / 2.0, math.cos(theta), -math.sin(theta))]
    elif obj_type == 't_junction':
        arm = float(obj.get('arm_length_m', 12.0))
        local = [(-arm, 0.0, 1.0, 0.0), (+arm, 0.0, 1.0, 0.0), (0.0, -arm, 0.0, 1.0)]
    elif obj_type == 'cross_intersection':
        arm = float(obj.get('arm_length_m', 12.0))
        local = [(-arm, 0.0, 1.0, 0.0), (+arm, 0.0, 1.0, 0.0), (0.0, +arm, 0.0, 1.0), (0.0, -arm, 0.0, 1.0)]
    else:
        return []
    result = []
    for lx, ly, ltx, lty in local:
        x, y = local_to_world_design(obj, lx, ly)
        tx, ty = _rotate_vector_world(ltx, lty, rotation)
        mag = math.hypot(tx, ty)
        if mag <= 1e-09:
            continue
        result.append({'x': x, 'y': y, 'tx': tx / mag, 'ty': ty / mag, 'width_m': width, 'object_id': obj.get('id')})
    return result

def _axis_alignment(a, b):
    """Return absolute tangent-axis alignment in [0,1]."""
    return abs(a['tx'] * b['tx'] + a['ty'] * b['ty'])

def spawn_connection_patches(qlabs, objects):
    """Bridge tiny rendering seams only at actual road connections."""
    endpoints = []
    for obj in objects:
        endpoints.extend(_connection_points_design(obj))
    used_pairs = set()
    for i, a in enumerate(endpoints):
        for j in range(i + 1, len(endpoints)):
            b = endpoints[j]
            if a.get('object_id') == b.get('object_id'):
                continue
            dx = b['x'] - a['x']
            dy = b['y'] - a['y']
            distance = math.hypot(dx, dy)
            if distance > JOIN_MATCH_TOLERANCE_DESIGN_M:
                continue
            if _axis_alignment(a, b) < math.cos(math.radians(12.0)):
                continue
            pair_key = tuple(sorted((i, j)))
            if pair_key in used_pairs:
                continue
            used_pairs.add(pair_key)
            cx_design = (a['x'] + b['x']) / 2.0
            cy_design = (a['y'] + b['y']) / 2.0
            dot = a['tx'] * b['tx'] + a['ty'] * b['ty']
            sign = 1.0 if dot >= 0.0 else -1.0
            tx = a['tx'] + sign * b['tx']
            ty = a['ty'] + sign * b['ty']
            mag = math.hypot(tx, ty)
            if mag <= 1e-09:
                tx, ty = (a['tx'], a['ty'])
            else:
                tx /= mag
                ty /= mag
            half_patch = JOIN_PATCH_LENGTH_DESIGN_M / 2.0
            p1_design = (cx_design - tx * half_patch, cy_design - ty * half_patch)
            p2_design = (cx_design + tx * half_patch, cy_design + ty * half_patch)
            scale = project_scale()
            p1 = (p1_design[0] * scale, p1_design[1] * scale)
            p2 = (p2_design[0] * scale, p2_design[1] * scale)
            patch_width = max(a['width_m'], b['width_m']) * scale
            spawn_straight_spline(qlabs, p1, p2, patch_width, ROAD_COLOR, z=ROAD_Z + 0.0005)

def actor_effective_scale(obj):
    multiplier = max(0.001, float(obj.get('actor_scale', 1.0)))
    if bool(obj.get('scale_with_project', True)):
        multiplier *= project_scale()
    return multiplier

def _register_actor_handle(obj, actor):
    """Expose an actor by both stable object id and readable identifier."""
    object_id = str(obj.get('id', ''))
    identifier = str(obj.get('identifier', ''))
    if object_id:
        ACTOR_HANDLES[object_id] = actor
    if identifier:
        ACTOR_HANDLES[identifier] = actor

def spawn_scene_actor(qlabs, obj):
    global NEXT_SECONDARY_QCAR_ACTOR_NUMBER
    obj_type = str(obj.get('type', ''))
    yaw = editor_yaw_to_qlabs_radians(obj.get('rotation_deg', 0.0))
    actor_scale = actor_effective_scale(obj)
    uniform_scale = [actor_scale, actor_scale, actor_scale]
    configuration = int(obj.get('configuration', 0))
    if obj_type == 'median_wall':
        scale = project_scale()
        length = max(0.05, float(obj.get('length_m', 20.0)) * scale)
        width = max(0.02, float(obj.get('width_m', 0.6)) * scale)
        height = max(0.02, float(obj.get('height_m', 0.85)) * scale)
        actor = QLabsBasicShape(qlabs)
        status, _actor_number = actor.spawn(location=[float(obj.get('x', 0.0)) * scale, float(obj.get('y', 0.0)) * scale, TRACK_BASE_Z + height / 2.0], rotation=[0.0, 0.0, yaw], scale=[length, width, height], configuration=QLabsBasicShape.SHAPE_CUBE, waitForConfirmation=True)
        if status != 0:
            print('Unable to spawn median wall', obj.get('id'), 'status', status)
            return None
        actor.set_material_properties(color=[0.67, 0.65, 0.6], roughness=0.85, metallic=False, waitForConfirmation=True)
        actor.set_enable_dynamics(False, waitForConfirmation=True)
        actor.set_enable_collisions(True, waitForConfirmation=True)
        return actor
    return None

def spawn_scene_actors(qlabs, objects):
    scene_types = {'median_wall'}
    for obj in objects:
        obj_type = obj.get('type')
        if obj_type not in scene_types:
            continue
        if obj_type in {'person', 'animal', 'secondary_qcar2'} and str(obj.get('spawn_mode', 'immediate')) == 'triggered':
            continue
        actor = spawn_scene_actor(qlabs, obj)
        object_id = str(obj.get('id', ''))
        if actor is not None and object_id:
            _register_actor_handle(obj, actor)

def main():
    print('Connecting to QLabs...')
    qlabs = QuanserInteractiveLabs()
    if not qlabs.open('localhost'):
        print('Unable to connect to QLabs.')
        print('Open QLabs in the Open Road workspace and try again.')
        sys.exit(1)
    print('Connected to QLabs.')
    qlabs.destroy_all_spawned_actors()
    objects = TRACK_DATA.get('objects', [])
    for obj in objects:
        spawn_road_surface(qlabs, obj)
    spawn_connection_patches(qlabs, objects)
    for obj in objects:
        spawn_road_markings(qlabs, obj)
    spawn_scene_actors(qlabs, objects)
    print('QLabs track created. Project scale = ' + str(TRACK_DATA.get('project', {}).get('scale_name', '1:1')))
if __name__ == '__main__':
    main()
